PackageIdentifier: OrbitaChat.OrbitaChat
PackageVersion: 1.0.22
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/orbitachat/orbita-desktop/releases/download/v1.0.22/setup_1.0.22.exe
    InstallerSha256: 9BC11B39015C88E0EBD12C77891B7ACA98163C75664F55094E4186DDD61647DE
    ProductCode: com.saizzi.orbita
ManifestType: installer
ManifestVersion: 1.6.0
