PackageIdentifier: OrbitaChat.OrbitaChat
PackageVersion: 1.0.22
PackageLocale: ru-RU
Publisher: Saizzi
PublisherUrl: https://github.com/orbitachat/orbita-desktop
PublisherSupportUrl: https://github.com/orbitachat/orbita-desktop/issues
Author: Saizzi
PackageName: orbitachat
PackageUrl: https://github.com/orbitachat/orbita-desktop
License: GPL-3.0
LicenseUrl: https://github.com/orbitachat/orbita-desktop/blob/main/LICENSE
Copyright: Copyright (c) Saizzi
ShortDescription: Десктопное приложение OrbitaChat
Description: Быстрый, безопасный и современный десктопный мессенджер.
Tags:
  - orbitachat
  - orbita
  - чат
  - мессенджер
  - общение
  - electron
ManifestType: locale
ManifestVersion: 1.6.0
