PackageIdentifier: OrbitaChat.Orbita
PackageVersion: 1.0.22
PackageLocale: en-US
Publisher: Saizzi
PublisherUrl: https://github.com/orbitachat/orbita-desktop
PublisherSupportUrl: https://github.com/orbitachat/orbita-desktop/issues
Author: Saizzi
PackageName: Orbita
PackageUrl: https://github.com/orbitachat/orbita-desktop
License: GPL-3.0
LicenseUrl: https://github.com/orbitachat/orbita-desktop/blob/main/LICENSE
Copyright: Copyright (c) Saizzi
ShortDescription: Orbita Desktop application
Description: Fast, secure and modern desktop messaging application.
Moniker: orbita
Tags:
  - chat
  - messenger
  - communication
  - electron
  - orbitachat
ManifestType: defaultLocale
ManifestVersion: 1.6.0
